---
- hosts: all
  tasks:
    - name: ensure nginx is at the latest version
      apt: name=nginx state=latest
    - name: start nginx
      service:
          name: nginx
          state: started
# - name: Changing the content in the root directory
#   copy: 
#     content: "This is the new code deployed"
#     dest: /var/www/html/index.nginx-debian.html